sudo: false
cache: pip
language: python
python: 3.6

env:
    - TOX_ENV=pypy-django11
    - TOX_ENV=py27-django11
    - TOX_ENV=py35-django11
    - TOX_ENV=py35-django20
    - TOX_ENV=py36-django11
    - TOX_ENV=py36-django20
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=coveralls

install:
    - pip install --upgrade pip
    - pip install tox

script:
    tox -e $TOX_ENV

